language: python
python:
  - "3.6"
  - "3.6-dev"
install:
  - pip install Incantation
  - pip install flask
  - pip install codecov
  
script:
  - coverage run ./test/test.py
after_success:
  - codecov
